@base_url = http://localhost:5108/api

# Livro #############################

###Cadastro de um novo livro
POST {{base_url}}/livro/cadastrar
Content-Type: application/json

{
    "Titulo": "Orgulho e Preconceito",
    "Genero": "Romance",
    "AutorId": 2,
    "NumeroExemplares": 10
}

###Obtenção de todos os livros
GET {{base_url}}/livro/listar
Content-Type: application/json

###Remoção de um livro
DELETE {{base_url}}/livro/deletar/fcd6a685-2037-4c3a-a116-875394e1b47f
Content-Type: application/json

###Alteração de um livro
PUT {{base_url}}/livro/alterar/58f58dd4-a6cd-4e04-9056-a53e33dee115
Content-Type: application/json

{
    "Titulo": "Teste",
    "Genero": "Qualquer coisa",
    "AutorId": 1,
    "NumeroExemplares": 5
    
}

# Autor #############################

###Cadastro de um novo autor
POST {{base_url}}/autor/cadastrar
Content-Type: application/json

{
    "Nome": "Jane Austen",
    "Nacionalidade": "Inglesa",
    "DataNascimento": "1775-12-16"
}

###Obtenção de todos os autores
GET {{base_url}}/autor/listar
Content-Type: application/json
