@base_url = http://localhost:5108/api

# Livro #############################

###Cadastro de um novo livro
POST {{base_url}}/livro/cadastrar
Content-Type: application/json

{
    "Titulo": "Orgulho e Preconceito",
    "Genero": "Romance",
    "AutorId": 1,
    "NumeroExemplares": 10
}

###Obtenção de todos os livros
GET {{base_url}}/livro/listar
Content-Type: application/json

###Remoção de um livro
DELETE {{base_url}}/livro/deletar/c1f1cd19-040f-427d-9b8b-99f45f7e6dd2
Content-Type: application/json

###Alteração de um livro
PUT {{base_url}}/livro/alterar/01ce27b6-6b9f-49fb-b820-f6d3f9337640
Content-Type: application/json

{
    "Titulo": "Teste",
    "Genero": "Qualquer coisa",
    "AutorId": 1,
    "NumeroExemplares": 5
    
}

# Autor #############################

###Cadastro de um novo autor
POST {{base_url}}/autor/cadastrar
Content-Type: application/json

{
    "Nome": "Jane Austen",
    "Nacionalidade": "Inglesa",
    "DataNascimento": "1775-12-16"
}

###Obtenção de todos os autores
GET {{base_url}}/autor/listar
Content-Type: application/json
